### ISSUE TITLE
Normalize URIs when verifying solid:oidcIssuer

### ISSUE THREAD

**Issue by elf-pavlik** [CommunitySolidServer/access-token-verifier#214]
I mentioned it https://github.com/solid/solid-oidc/issues/38#issuecomment-1264410498

> I think we should actually recommend normalizing the issuer IRI before trying to match it.

> This comes especially important for authority with an empty path. Since `https://op.example` is equivalent to `https://op.example/`, IMO the issuer check MUST NOT fail due to this difference.

> https://www.rfc-editor.org/rfc/rfc3986#section-6.2.3

Possibly something like  https://www.npmjs.com/package/normalize-url could be used for that

**Comment by matthieubosquet** [comment]
> Normalizing the URL is getting into dangerous territory. OpenID and OAuth have historically replied on String comparisons for this. You can see this in the spec references above. I would highly, highly recommend not doing anything different for Solid.
> — https://github.com/solid/solid-oidc/issues/38#issuecomment-1264482930

As per above comment and [intended resolution](https://github.com/solid/solid-oidc/issues/38#issuecomment-1264498910) in terms of Solid OIDC spec, I'll close this issue.
